---
- name: cicd
  hosts: all
  tasks: 
    - name: env debug
      debug:
        msg: {{ ip_addr }}
    - name: configure DNS server
      copy:
        dest: /etc/resolve.conf
        content: |+
          nameserver 8.8.8.8
          nameserver 8.8.4.4
